### ISSUE TITLE
Scrapers sénat

### ISSUE THREAD

**Issue by njoyard** [SocieteCitoyenne/FranceData#4]
Je vais faire des modifs pour scraper le sénat.

L'idée que j'ai c'est d'inclure le scraping dans ceux de l'assemblée pour en gros avoir les mêmes JSON et les mêmes entités que ceux qui existent déjà, mais légèrement modifiés.

Je voudrais ajouter une propriété "chambre" (AN/SEN) à chaque entité, et aussi revoir les identifiants (l'URI n'a plus tellement de sens vu qu'on a 2 sites distincts). Je pensais à quelque chose du genre "type/chambre/session/numero", par exemple "scrutin/SEN/2015/144".

Dis-moi ce que tu en penses @jpic. Dans tous les cas je le ferai sur une branche dédiée. Au passage le scraping du sénat c'est de la boucherie industrielle (div id="wysiwyg" et rien de structuré dedans...). Dommage que les amendements au PJL Lemaire concernant le parlement aient été giclés...

**Comment by jpic** [comment]
Je crois bien que c'est la même boucherie sur l'a-n, mais en moins pire ^^

Peut-être qu'on peut remplacer l'URI par l'URL absolue ?

**Comment by njoyard** [comment]
C'est une option, en effet.

**Comment by jpic** [comment]
Je me demande si ça pourrait être utile pour rafraichir un dossier

**Comment by njoyard** [comment]
Bon du coup j'ai mis l'URL complête, qui pourra servir d'identifiant dans FD. Les scrapers sénat sont terminés (branche senat), il faudra probablement updater un ou deux trucs dans l'appli. Mais je vais me concentrer sur memopol et d-r[-v] pour avoir un multi-chambre fonctionnel au plus vite :)

**Comment by jpic** [comment]
Du coup, y'a des PRs prêtes à merger ?

**Comment by njoyard** [comment]
Maintenant oui :)
